### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by zhishu520** [koirand/pulp#46]
![image](https://user-images.githubusercontent.com/8665898/57297663-c4f87000-7102-11e9-8d97-6142426b9e4f.png)

hugo version: 0.55

**Comment by koirand** [comment]
Try to add taxonomies setting to your config.toml.

https://github.com/koirand/pulp/blob/d9fb5363451420dc5ae1bc1e85e7b8e5eb66d0be/exampleSite/config.toml#L10-L12

**Comment by koirand** [comment]
Or, adding listPageDateFormat setting in main section may be fine.

https://github.com/koirand/pulp/blob/d9fb5363451420dc5ae1bc1e85e7b8e5eb66d0be/exampleSite/config.toml#L22

**Comment by zhishu520** [comment]
thanks. QAQ
