### ISSUE TITLE
something wrong.

### ISSUE THREAD

**Issue by baihat** [koirand/pulp#50]
Building sites … ERROR 2019/05/16 20:51:19 render of "taxonomyTerm" failed: "G:\blog\themes\pulp\layouts\_default\list.html:12:55": execute of template failed: template: _d efault\list.html:12:55: executing "main" at <.Site.Params.listpagedateformat>: invalid value; expected string
Total in 36 ms
Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "G:\blog\themes\pulp\layouts\_default\list.html:12:55": execute of template failed: template: _default\list.html:12:55: executing "main" at <.Site.Params.listpagedateformat>: invalid value; expected string

**Comment by koirand** [comment]
Add listPageDateFormat setting to your config.toml by referring to [exampleSite](https://github.com/koirand/pulp/tree/d9fb5363451420dc5ae1bc1e85e7b8e5eb66d0be/exampleSite).
https://github.com/koirand/pulp/blob/d9fb5363451420dc5ae1bc1e85e7b8e5eb66d0be/exampleSite/config.toml#L22
