### ISSUE TITLE
_index.md not showing any content.

### ISSUE THREAD

**Issue by diarmaid-mcmanus** [koirand/pulp#54]
Per https://github.com/diarmaid-mcmanus/site/blob/master/content/archive/_index.md, which generates into https://diarmaidmcmanus.com/archive/

I've tried create a new page on my site using pulp, living under /archive/. 

I've tried the page with the following along with title in the opening block :

---
date: 2019-06-05T12:00:00Z
draft: false
---

The page itself generates, but no content is displayed. I do not see any warnings or errors when hugo is ran, nor when ran with hugo -v

I've also tried this using `hugo new arkive/_index.md`, which has the same problem - see https://diarmaidmcmanus.com/arkive/

**Comment by diarmaid-mcmanus** [comment]
hugo version
Hugo Static Site Generator v0.55.6 linux/amd64 BuildDate: 2019-05-18T11:36:07Z

**Comment by koirand** [comment]
Hi.
Files with names beginning with an underscore may be ignored.
This is the go language specification used by HUGO.
https://stackoverflow.com/questions/25161774/what-are-conventions-for-filenames-in-go
Please consider another file name.

**Comment by diarmaid-mcmanus** [comment]
Thanks. Based on https://gohugo.io/content-management/organization/#index-pages-index-md I had a misunderstanding about how I should name the file, but using 'index.md' instead of '_index.md' correctly generates the page as I was expecting.

Sorry for taking up your time!

**Comment by laurauzcategui** [comment]
Hi @koirand , 

I was taking a look to update my site using pulp but I found out that as @diarmaid-mcmanus  mentioned previously index files are not rendering the text. Do you know why that might be? 

Cheers ,
