### ISSUE TITLE
Extra closing braces in layouts/partials/header.html

### ISSUE THREAD

**Issue by mpjashby** [koirand/pulp#56]
https://github.com/koirand/pulp/commit/acf8d53cdd1d1f5d4a83863e7ca9751df28b7c5b seems to have added two extra closing braces on line 5 of https://github.com/koirand/pulp/blob/6a65b973393e75d253ff5b279b7f74b0eca5fd88/layouts/partials/header.html#L5 so the line reads:

```
<a href="{{ .Site.BaseURL }}"><img src="{{ .Site.BaseURL }}/img/avatar-border.svg" }}></a>
```

instead of 

```
<a href="{{ .Site.BaseURL }}"><img src="{{ .Site.BaseURL }}/img/avatar-border.svg"></a>
```

Causing an error in validating the resulting HTML.

**Comment by koirand** [comment]
Thanks for letting me know. I'll fix it.
