### ISSUE TITLE
When blog tag feature would be added to the pulp

### ISSUE THREAD

**Issue by Jalr4ever** [koirand/pulp#65]
😭 pls ！

**Comment by koirand** [comment]
OK, I will try it.

**Comment by koirand** [comment]
Screenshots

<img width="441" alt="ss-top" src="https://user-images.githubusercontent.com/17229643/72672672-bd16fc80-3a01-11ea-9056-7439db39ed75.png">

<img width="441" alt="ss-list" src="https://user-images.githubusercontent.com/17229643/72672673-c607ce00-3a01-11ea-8356-d3cfc4ead65e.png">

<img width="441" alt="ss-page" src="https://user-images.githubusercontent.com/17229643/72672675-cacc8200-3a01-11ea-914e-c80876d03b16.png">
