### ISSUE TITLE
search does not scale to 100% on firefox (works on chrome)

### ISSUE THREAD

**Issue by rompic** [koirand/pulp#66]
![grafik](https://user-images.githubusercontent.com/6322123/71640442-587e4280-2c8a-11ea-92e2-fcb483a48595.png)

![grafik](https://user-images.githubusercontent.com/6322123/71640445-6b911280-2c8a-11ea-8aa4-269209814083.png)

**Comment by koirand** [comment]
Hello, Thank you for letting me know. I have fix it !

**Comment by rompic** [comment]
thanks for the fast fix :)
